### ISSUE TITLE
Test Data Range

### ISSUE THREAD

**Issue by kesslerd** [kesslerd/dotnet_testat#12]
Dies sollte mindestens fünf Tests ergeben (2 gültige Kombination 3
ungültige Kombinationen von Datumswerten).

- [ ] Dritter Test für eine ungülitge Kombination von Datumswerten

**Comment by McDonnough** [comment]
Es fehlt noch ein dritter Test für eine ungülitge Kombination von Datumswerten.

**Comment by kesslerd** [comment]
Target.Add(new Reservation() { AutoId = 1, KundeId = 1, Von = new DateTime(2018, 01, 01), Bis = new DateTime(2017, 01, 02) });

Monat + Tag valid, aber Jahr nicht
